repos:

    - repo: local
      hooks:
        - id: update requirements
          name: update requirements
          entry:  python -m pip install --upgrade -r requirements.txt
          language: python
          always_run: true
          pass_filenames: false
          stages: ["push"]

        - id: test
          name: pytest
          entry: python -m pytest
          language: system
          always_run: true
          pass_filenames: false

        - id: mypy
          name: mypy
          entry: mypy streamlit_app.py
          language: system
          always_run: true
          pass_filenames: false

        - id: update-requirements
          name: Update and add requirements.txt
          entry: bash -c "pip freeze > requirements.txt && git add requirements.txt"
          language: system
          always_run: true
          files: ^requirements\.txt$